# Generated by Django 3.2.18 on 2023-04-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_group_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['day', '-time']},
        ),
    ]
