# Generated by Django 3.2.18 on 2023-04-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='group_size',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
