# Generated by Django 3.2.18 on 2023-04-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20230407_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['created_on', 'day', 'time']},
        ),
    ]
